AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
    - 'app/controllers/games_controller.rb'
    - 'app/controllers/pieces_controller.rb'
    - 'app/models/king.rb'
    - 'app/models/piece.rb'
    - 'spec/models/king_spec.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
