sudo: false
language: ruby
rvm:
  - 2.0.0
script: 
  - bundle exec rspec
  - bundle exec rubocop

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate